/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlegithubex;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appSuma() {
        App classUnderTest = new App();
        assertEquals(5, classUnderTest.sumar(1, 4));
    }
    @Test void appRestar() {
        App classUnderTest = new App();
        assertEquals(1, classUnderTest.restar(3, 2));
    }
}
